### ISSUE TITLE
用 node:alpine 是不是会更好

### ISSUE THREAD

**Issue by blade254353074** [Dafrok/webpack2-docker#1]

**Comment by Dafrok** [comment]
有道理

**Comment by blade254353074** [comment]
我可以发 pr 么

**Comment by Dafrok** [comment]
发吧。。。其实我还没搞懂 VOLUME 挂载的问题，还要改的

**Comment by Dafrok** [comment]
不过用 alpine 原本的意义就失去了，因为的目的是在同一台机器上统一环境的版本，可以应对不同的项目使用指定的 node / webpack / etc. 版本运行，alpine 符合我的需求吗？

**Comment by blade254353074** [comment]
可以先试试，麻雀虽小五脏俱全
